### ISSUE TITLE
Using standard icons with Cordova Android 8+ defaulting to the adaptive icons

### ISSUE THREAD

**Issue by goldfire** [dwmkerr/app-icon#100]
Before cordova-android 8.0, generating the standard image icons worked fine. However, there now seems to be a default adapative icon with the cordova logo that is being used even when generating the image icons with `app-icon generate`. There correct icons are in the file, but the ic_launcher.xml files look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
```

Am I overlooking something or is app-icon not handling this correctly?

**Comment by dwmkerr** [comment]
Hi - I actually provided a feature to generate adaptive icons, just
finished a few days ago. By using this, it *should* overwrite the adaptive
icons generated by Cordova. If you install the latest version, and run:

    app-icon init —adaptive-icons
    app-icon generate —adaptive-icons

Does it work? Note it is a double dash before the flag, I’m on my phone and
it’s converting it to a long dash.

If this fixes it, it increases the urgency of the feature which warns if
extraneous icons are detected.

**Comment by goldfire** [comment]
Sorry about the delay and thanks for the quick response! It seems to be working well using that method, thanks!

**Comment by dwmkerr** [comment]
Great, thanks!
