### ISSUE TITLE
init --adaptive-icons: background/foreground swapped?

### ISSUE THREAD

**Issue by drewcovi** [dwmkerr/app-icon#104]
it seems the background and foreground are swapped in the init command. unless I'm misunderstanding the intent, background should always be opaque and the foreground layer can support alpha channel.

**Comment by drewcovi** [comment]
disregard, the background.png looked like a typical transparent png at first (due to the gray and white grid) turns out this was actually an intended checkerboard background, and fully opaque

**Comment by dwmkerr** [comment]
OK no worries, thanks @drewcovi! I'm thinking about re-doing the default icon as it might be a bit confusing!
