### ISSUE TITLE
Splash screens

### ISSUE THREAD

**Issue by benjick** [dwmkerr/app-icon#13]
Hey, would it be possible to generate splash screens with this as well?

**Comment by dwmkerr** [comment]
Hi @benjick good idea! I'm in the process of testing the library against a whole bunch of projects, react native, cordova, native, xamarin etc. I'm thinking of renaming it to be more general as it actually works perfectly well with many project types. I can also look into splash screens at the same time

**Comment by fiznool** [comment]
Just weighing in here to say thanks for a fantastic library - works perfectly with React Native. A separate splashscreen package would be awesome: `app-splashscreen` is still available on npm :smile:

**Comment by dwmkerr** [comment]
Seems like this could be a popular addition!

@fiznool @benjick any thoughts on what would be better, a separate CLI or a single CLI with multiple flags? I'm leaning towards separate to follow the Unix philosophy of small, focused tools, but would love your thoughts!

**Comment by fiznool** [comment]
My vote would be for a separate cli, this is sufficiently different IMHO to
justify this.

**Comment by dwmkerr** [comment]
Sounds good, will get started when I get some quiet time!

**Comment by dwmkerr** [comment]
I've started on this now:

https://github.com/dwmkerr/app-splash

I'll close this thread and it can be picked up over on the other repo now 😄

**Comment by fiznool** [comment]
Do you mean

https://github.com/dwmkerr/app-splash

?

**Comment by dwmkerr** [comment]
Whoops yes, fixed the comment :)
