### ISSUE TITLE
 Cannot be used on Windows 10 command line.

### ISSUE THREAD

**Issue by ichingsoft** [dwmkerr/app-icon#134]
```shell
$ app-icon generate
  Error: ImageMagick must be installed. Try:
    brew install imagemagick
```

My magick version is:
```shell
$ magick --version
Version: ImageMagick 7.0.10-14 Q16 x64 2020-05-23 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```

**Comment by daominhsangvn** [comment]
You must install following version of magick: `ImageMagick-7.0.10-24-Q16-HDRI-x64-dll.exe` and tick "Install legacy utilities (e.g. convert)" while setup

**Comment by ichingsoft** [comment]
> You must install following version of magick: `ImageMagick-7.0.10-24-Q16-HDRI-x64-dll.exe` and tick "Install legacy utilities (e.g. convert)" while setup

Thank you, "Install legacy utilities (e.g. convert)" must be selected.
