### ISSUE TITLE
Find AndroidManifests in a Cordova project should exclude CordovaLib/ dir

### ISSUE THREAD

**Issue by ath0mas** [dwmkerr/app-icon#139]
Like checked in corresponding spec, finding the Cordova manifests returns the one located in CordovaLib/ in addition to the main one.

https://github.com/dwmkerr/app-icon/blob/ddd3fd23661665dfc1565e584aafaeb93b542a13/src/android/find-android-manifests.specs.js#L17-L22

Is that detection made on purpose?

To my experience, `CordovaLib/` should be excluded so that generating icons is only done for main and not for this utility lib dir.
Can I prepare a PR to change this behavior?

**Comment by dwmkerr** [comment]
Yes no problems!
