### ISSUE TITLE
Question: Is there an option to generate icon only for one platform?

### ISSUE THREAD

**Issue by vieraleonel** [dwmkerr/app-icon#32]
I would like to have different icons for Android and iOS (just for the background). Thanks. Great Work!

**Comment by dwmkerr** [comment]
Hi @vieraleonel great idea! I was thinking that maybe just adding a 'platform' flag would work, so it would be two calls like this:

```bash
app-icon -i android.png --platform android
app-icon -i ios.png --platform ios
```

This means we can add one new flag, instead of potentially two (like `--icon-ios` or `--icon-android`). Would that work for you?

**Comment by vieraleonel** [comment]
That would be excellent!

**Comment by dwmkerr** [comment]
Try installing version 0.5, just published:

```bash
app-icon generate -i android.png --platforms android
app-icon generate -i ios.png --platforms ios
```

**Comment by vieraleonel** [comment]
Working great! Just to make it perfect you should update README and **--help** option. I can make a PR this weekend if you like.

**Comment by vieraleonel** [comment]
Sorry I just see **--help** option has the documentation. So only a README update

**Comment by dwmkerr** [comment]
@vieraleonel good point, I totally forgot the `README`! I'll update it 👍

**Comment by dwmkerr** [comment]
I think we're covered with #35 now 😄
