### ISSUE TITLE
iOS asset sizes incorrect

### ISSUE THREAD

**Issue by dominictracey** [dwmkerr/app-icon#40]
Seems to create many of the proper file names, but the sizes are incorrect for the iOS images.xcassets. Xcode errors like:

`proj/ios/Hangboard/Images.xcassets: warning: Ambiguous Content: AppIcon.appiconset/ipad-29x29-2x.png is 29x29 but should be 58x58.
`

the 29x29-1x and 2929-2x are both 29x29.

Xcode 8.3.3
RN 0.47.1

Thanks for the otherwise great tool - Android works great!

**Comment by JCMais** [comment]
They are correct here, check if you imagemagick version is updated

**Comment by dwmkerr** [comment]
Hmm definitely something strange - I wonder if the scaling is not being applied properly, potentially the `-2x` on the image is not being applied, although I thought I'd tested this. 

I'll add a test case to assert that an image which needs scaling is sized appropriately and we can check then, the only issue is that it'll take a week or two as I am swamped at work

**Comment by dominictracey** [comment]
@JCMais imagemagick 7.0.7

@dwmkerr thanks - I worked around it for the interim.

**Comment by kasperg** [comment]
I am also seeing this. Same versions of ImageMagick, XCode and React Native as @dominictracey.

**Comment by kasperg** [comment]
Found out what my problem was. I used [`react-native-icon`](https://www.npmjs.com/package/react-native-icon) which only goes to 0.2.1. After switching to [`app-icon`](https://www.npmjs.com/package/app-icon) files are generated as expected. 🤦‍♂️

**Comment by dwmkerr** [comment]
Oh OK cool - just to sanity check, does that mean @kasperg that for images which are `2x` scale, you get the right size (e.g. 29x29 2x comes out as 58x58?)

**Comment by kasperg** [comment]
@dwmkerr Yes.

I think it would be nice to deprecate `react-native-icon` for good measure. It is still getting quite a few downloads.

**Comment by dwmkerr** [comment]
Good point, I'll raise a ticket to do this, thanks mate!

**Comment by dwmkerr** [comment]
Raised #42

**Comment by sfratini** [comment]
FYI this still happens on `0.13.2` if the original logo is not a perfect square, although I assume imagemagik is just scaling and not "deforming" the image on purpose.
