### ISSUE TITLE
icon generation breaks if directory contains a space

### ISSUE THREAD

**Issue by sgdesmet** [dwmkerr/app-icon#44]
Paths supplied to `convert` are not escaped or quoted, which causes issues if the path contains a space

    Failed to call 'convert res/icon/universal/logo.png -resize 1024x1024 platforms/ios/Sample Project/Images.xcassets/AppIcon.appiconset/ios-marketing-1024x1024-1x.png. Error is 'Command failed: convert res/icon/universal/logo.png -resize 1024x1024 platforms/ios/Sample Project/Images.xcassets/AppIcon.appiconset/ios-marketing-1024x1024-1x.png
    convert: unable to open image 'platforms/ios/Sample': No such file or directory @ error/blob.c/OpenBlob/3109.
    convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/509.
    convert: unable to open image 'Project/Images.xcassets/AppIcon.appiconset/ios-marketing-1024x1024-1x.png': No such file or directory @ error/blob.c/OpenBlob/3109.
    convert: WriteBlob Failed `Project/Images.xcassets/AppIcon.appiconset/ios-marketing-1024x1024-1x.png' @ error/png.c/MagickPNGErrorHandler/1711.

**Comment by sgdesmet** [comment]
See pull request #45

**Comment by dwmkerr** [comment]
Fixed in v0.6.3 - thanks for the help @sgdesmet!
