### ISSUE TITLE
Missing icon sizes for react-native iOS

### ISSUE THREAD

**Issue by nachocifu** [dwmkerr/app-icon#46]
-  Iphone Notification ios7-11 20pt 2x
-  Iphone Notification ios7-11 20pt 3x
-  Iphone Spotlight - 5,6 Settings - iOS 5 29pt 3x
- Iphone Spotlight - ios7-11 40pt 3x
- Iphone App iOS 7-11 60pt 3x
- Ipad Notifications iOS 7-11 20pt 1x
- Ipad Notifications iOS 7-11 20pt 2x
- iPad pro app iOS 9-11 83.5pt 2x
- App Store iOS 1024pt

**Comment by dwmkerr** [comment]
Oh damn, that's a lot. Thanks for sharing, I'll look into this soon, unless you have a PR?

**Comment by nachocifu** [comment]
Don't have a PR, to much on my plate. Trying to fix this manually. 
Another image missing according to apple is:
"Missing required icon file - The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."
PS: loved the module, migrating an entire app from ionic to react and this helped big time with the icons.

**Comment by amestsantim** [comment]
I was going to work on this issue but then I looked at the Contents.json file for a recent app I published to the iTunes store and it is pretty much the same as the template in app-icon.
I don't think there are any missing files to generate (add to the template).

**Comment by dwmkerr** [comment]
Yeah I had a look a while ago and wasn't sure which ones are missing, so I might just close this soon unless I get more questions from people.

**Comment by amestsantim** [comment]
Yeah, in the meanwhile please mark the issues 'help wanted' that you think should be worked on. I have some time.

**Comment by dwmkerr** [comment]
Sure, I'll add a few now @amestsantim
