### ISSUE TITLE
Not all icons are generated (delete icon no needed?)

### ISSUE THREAD

**Issue by obsidianart** [dwmkerr/app-icon#71]
I started my project from a boilerplate (from infinte red) and I used your app like I did in the past but it didn't work on some phone.
After a lot of research I think I found the problem: *some icons are not generated*.
It is likely that they are not needed, but if present they are used, probably the script should remove those:
- /android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
- /android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
- /android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
- /android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
- /imagzle/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png

Thanks for your amazing work.

**Comment by dwmkerr** [comment]
Thanks @obsidianart! This is now resolved in version `0.10.0`, which generates the `_round` files as well, over-writing ones which will have been created by Android Studio.
