### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by aeirola** [dwmkerr/app-icon#74]
Hey, the tool looks nice, but seems to lack support for SVG source images. I think it would be really nice to be able to only store SVG images in the code repository, and generate PNG rasters of them on build. SVG images have the benefit of being scalable to any resolution without dithering, and easy to edit by developers without having to install heavy image editing tools. Are there any plans on supporting SVGs in the future?

In the long run, SVG support could even enable support for generating Android Vector Drawable icons.

**Comment by mifi** [comment]
https://github.com/lovell/sharp supports easily converting svg to png and could be used by this module. Note it is a native module.

**Comment by dwmkerr** [comment]
If it wasn't for the fact that Android supports vector icons, then I'd say we should follow the Unix philosophy and let another tool do the job, e.g. `imagemagick`. But this sounds like a valid feature request so will look into it!

**Comment by aeirola** [comment]
I decided to go a different route and create a separate tool for SVG-based application icons with https://github.com/aeirola/react-native-svg-app-icon which builds on the idea of Android adaptive icons to generate all icon types, including adaptive icons, from a single SVG image.

I'll go ahead and close the issue, as I personally don't have a need for SVG support myself anymore. If someone else still feels that SVG support should be added to app-icon, feel free to reopen the issue.
